### ISSUE TITLE
Change the default branch from `master` to `main`

### ISSUE THREAD

**Issue by vasilmkd** [ktoso/sbt-jcstress#15]
@eed3si9n Can you please help me with this one? I would appreciate it very much. Unfortunately, I do not have the proper permissions to do it myself. Sorry for the inconvenience.

**Comment by eed3si9n** [comment]
Happy to oblige - https://github.com/sbt/sbt-jcstress/branches

**Comment by vasilmkd** [comment]
Thank you very much!
