### ISSUE TITLE
"pl.project13.scala" or "pl.project13.sbt"

### ISSUE THREAD

**Issue by jiminhsieh** [ktoso/sbt-jcstress#8]
I found that example in README uses `pl.project13.sbt` , but `build.sbt` uses `pl.project13.scala`.

**Comment by ktoso** [comment]
I think the source is correct hmmm, will check in bintray

**Comment by ktoso** [comment]
.scala is correct https://bintray.com/ktosopl/sbt-plugins/sbt-jcstress/0.2.0#files/pl.project13.scala%2Fsbt-jcstress%2Fscala_2.12%2Fsbt_1.0%2F0.2.0%2Fjars

though maybe this should be changed actuallly

**Comment by jiminhsieh** [comment]
I found one thing. You actually released two versions of `sbt-jcstress` in version 0.1.0. to Bintray. One comes with `sbt 0.13`, another comes with `sbt 1.0`.
![screen shot 2017-11-18 at 11 44 05](https://user-images.githubusercontent.com/5125598/32976649-6cbfccdc-cc56-11e7-87d8-04e2678bc388.png)
I just thought it would be better to let you know. :)

**Comment by jiminhsieh** [comment]
I also found class path of sbt-jcstress is `pl.project13.sbt.jcstress` and sbt-jol is `pl.project13.sbt.jol`. But you used `pl.project13.scala.sbt` in sbt-jmh.
